[pytest]

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

addopts = -v

markers =
    smoke: Critical smoke tests
    regression: Full regression tests
    login: Login related tests
    cart: Shopping cart tests
    checkout: Checkout tests